### ISSUE TITLE
datapackage_uri and is_local properties

### ISSUE THREAD

**Issue by pwalsh** [tryggvib/datapackage#32]
Why do data packages created with `datapackage` have `datapackage_uri` and `is_local` properties?

They are not part of the spec, so I'm wondering what their purpose is, and, if I can suppress them?

Additionally, the `standard` property: also not part of the spec but of course I see the utility of this?

**Comment by tryggvib** [comment]
These are helper properties. In ``datapackage`` we can access the resources directly because they're just objects. However according to the specification we can define a ``base`` property and ``path`` in a resource is relative to that ``base`` (or if ``base`` is not defined its relative to the directory the descriptor file is in). So we needed a way of knowing from the resource how to treat the ``path``. It's an internal thing so you can suppress them or better yet, if you know of a better way around this (like always accessing resources from the datapackage) feel free to implement :wink:

Standard is just because the data package spec often introduces backwards incompatible changes and I would like to be able to mark what version of the spec is being used. This could probably be improved upon.

**Comment by pwalsh** [comment]
Thanks for the explanation. It sounds fine (and reasonable). If I understand you correctly, they are really only required by an instance of DataPackage, and not in the output descriptor, right?

**Comment by tryggvib** [comment]
That's correct. Closing this issue now.
